In [1]:
import numpy as np

In [2]:
docs = ['recurrent neural network',
		'neural network',
		'artificial neural',
		'connections between nodes',
		'can create a cycle',
		'allowing output',
		'some nodes to affect subsequent',
		'exhibit temporal',
		'dynamic behavior',
		'type of Neural Network',
    'affect subsequent']

In [4]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer  # Import from tensorflow

# Now you can use the Tokenizer
tokenizer = Tokenizer(oov_token="<nothing>")





In [5]:
tokenizer.fit_on_texts(docs)

In [6]:
tokenizer.word_index


{'<nothing>': 1,
 'neural': 2,
 'network': 3,
 'nodes': 4,
 'affect': 5,
 'subsequent': 6,
 'recurrent': 7,
 'artificial': 8,
 'connections': 9,
 'between': 10,
 'can': 11,
 'create': 12,
 'a': 13,
 'cycle': 14,
 'allowing': 15,
 'output': 16,
 'some': 17,
 'to': 18,
 'exhibit': 19,
 'temporal': 20,
 'dynamic': 21,
 'behavior': 22,
 'type': 23,
 'of': 24}

In [7]:
tokenizer.word_counts

OrderedDict([('recurrent', 1),
             ('neural', 4),
             ('network', 3),
             ('artificial', 1),
             ('connections', 1),
             ('between', 1),
             ('nodes', 2),
             ('can', 1),
             ('create', 1),
             ('a', 1),
             ('cycle', 1),
             ('allowing', 1),
             ('output', 1),
             ('some', 1),
             ('to', 1),
             ('affect', 2),
             ('subsequent', 2),
             ('exhibit', 1),
             ('temporal', 1),
             ('dynamic', 1),
             ('behavior', 1),
             ('type', 1),
             ('of', 1)])

In [8]:
tokenizer.document_count

11

In [11]:
sequences=tokenizer.texts_to_sequences(docs)

In [12]:
#we can do padding.
#to get them in the same length.

from keras.utils import pad_sequences
nsequences = pad_sequences(sequences,maxlen = 10, padding ='post')
nsequences

array([[ 7,  2,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 8,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 9, 10,  4,  0,  0,  0,  0,  0,  0,  0],
       [11, 12, 13, 14,  0,  0,  0,  0,  0,  0],
       [15, 16,  0,  0,  0,  0,  0,  0,  0,  0],
       [17,  4, 18,  5,  6,  0,  0,  0,  0,  0],
       [19, 20,  0,  0,  0,  0,  0,  0,  0,  0],
       [21, 22,  0,  0,  0,  0,  0,  0,  0,  0],
       [23, 24,  2,  3,  0,  0,  0,  0,  0,  0],
       [ 5,  6,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [13]:
#sentiment Analysis using rnn
from keras.datasets import imdb
imdb.load_data()


17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

In [15]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten


In [16]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()



In [18]:
len(X_train[0])

218

In [19]:
from keras.utils import pad_sequences
maxlen=500
X_train = pad_sequences(X_train,maxlen = maxlen, padding ='post')
X_test = pad_sequences(X_test,maxlen = maxlen, padding ='post')
X_train

array([[   1,   14,   22, ...,    0,    0,    0],
       [   1,  194, 1153, ...,    0,    0,    0],
       [   1,   14,   47, ...,    0,    0,    0],
       ...,
       [   1,   11,    6, ...,    0,    0,    0],
       [   1, 1446, 7079, ...,    0,    0,    0],
       [   1,   17,    6, ...,    0,    0,    0]], dtype=int32)

In [20]:
X_train[0]

array([    1,    14,    22,    16,    43,   530,   973,  1622,  1385,
          65,   458,  4468,    66,  3941,     4,   173,    36,   256,
           5,    25,   100,    43,   838,   112,    50,   670, 22665,
           9,    35,   480,   284,     5,   150,     4,   172,   112,
         167, 21631,   336,   385,    39,     4,   172,  4536,  1111,
          17,   546,    38,    13,   447,     4,   192,    50,    16,
           6,   147,  2025,    19,    14,    22,     4,  1920,  4613,
         469,     4,    22,    71,    87,    12,    16,    43,   530,
          38,    76,    15,    13,  1247,     4,    22,    17,   515,
          17,    12,    16,   626,    18, 19193,     5,    62,   386,
          12,     8,   316,     8,   106,     5,     4,  2223,  5244,
          16,   480,    66,  3785,    33,     4,   130,    12,    16,
          38,   619,     5,    25,   124,    51,    36,   135,    48,
          25,  1415,    33,     6,    22,    12,   215,    28,    77,
          52,     5,

In [22]:
#MODEL Architecture.
#Now we split the dataset now , we have put it in an RNN
#Train it usin an RNN.
model = Sequential()
model.add(SimpleRNN(32,input_shape=(500,1),return_sequences=False))
model.add(Dense(1, activation ='sigmoid'))




In [23]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)             │ (None, 32)                  │           1,088 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.compile(metrics=['accuracy'],optimizer='adam',loss='binary_crossentropy')

In [28]:
#model training.
model.fit(X_train,y_train,epochs =5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 88s 110ms/step - accuracy: 0.5040 - loss: 0.6954 - val_accuracy: 0.5041 - val_loss: 0.6938
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 83s 106ms/step - accuracy: 0.5078 - loss: 0.6941 - val_accuracy: 0.4982 - val_loss: 0.6936
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 142s 106ms/step - accuracy: 0.5103 - loss: 0.6937 - val_accuracy: 0.5008 - val_loss: 0.6957
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 83s 106ms/step - accuracy: 0.5077 - loss: 0.6945 - val_accuracy: 0.5032 - val_loss: 0.6935
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 141s 106ms/step - accuracy: 0.5046 - loss: 0.6940 - val_accuracy: 0.5021 - val_loss: 0.6937


In [34]:
model.save('path.h5')


model.predict(X_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 25ms/step


array([[0.45582736],
       [0.47556952],
       [0.53796697],
       ...,
       [0.5202781 ],
       [0.49498034],
       [0.50817573]], dtype=float32)